/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChamadaRouteImport } from './routes/chamada'
import { Route as AuthenticatedEncerramentoRouteImport } from './routes/_authenticated/encerramento'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaRoute = ChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEncerramentoRoute =
  AuthenticatedEncerramentoRouteImport.update({
    id: '/encerramento',
    path: '/encerramento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chamada': typeof ChamadaRoute
  '/encerramento': typeof AuthenticatedEncerramentoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chamada': typeof ChamadaRoute
  '/encerramento': typeof AuthenticatedEncerramentoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chamada': typeof ChamadaRoute
  '/_authenticated/encerramento': typeof AuthenticatedEncerramentoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/chamada' | '/encerramento' | '/painel' | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chamada' | '/encerramento' | '/painel' | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chamada'
    | '/_authenticated/encerramento'
    | '/_authenticated/painel'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChamadaRoute: typeof ChamadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada': {
      id: '/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof ChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/encerramento': {
      id: '/_authenticated/encerramento'
      path: '/encerramento'
      fullPath: '/encerramento'
      preLoaderRoute: typeof AuthenticatedEncerramentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEncerramentoRoute: typeof AuthenticatedEncerramentoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEncerramentoRoute: AuthenticatedEncerramentoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChamadaRoute: ChamadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
